# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/external/UnrealEngine/UE_5.8/Linux_Unreal_Engine_5.8.0

TARGETS = \
	TheLure-Android-DebugGame  \
	TheLure-Android-Development  \
	TheLure-Android-Shipping  \
	TheLure-Linux-DebugGame  \
	TheLure-Linux-Development  \
	TheLure-Linux-Shipping  \
	TheLure-LinuxArm64-DebugGame  \
	TheLure-LinuxArm64-Development  \
	TheLure-LinuxArm64-Shipping  \
	TheLure \
	TheLureEditor-Linux-DebugGame  \
	TheLureEditor-Linux-Development  \
	TheLureEditor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TheLureEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TheLureEditor-Linux-Debug


TheLure-Android-DebugGame:
	 $(BUILD) TheLure Android DebugGame  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure-Android-Development:
	 $(BUILD) TheLure Android Development  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure-Android-Shipping:
	 $(BUILD) TheLure Android Shipping  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure-Linux-DebugGame:
	 $(BUILD) TheLure Linux DebugGame  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure-Linux-Development:
	 $(BUILD) TheLure Linux Development  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure-Linux-Shipping:
	 $(BUILD) TheLure Linux Shipping  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure-LinuxArm64-DebugGame:
	 $(BUILD) TheLure LinuxArm64 DebugGame  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure-LinuxArm64-Development:
	 $(BUILD) TheLure LinuxArm64 Development  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure-LinuxArm64-Shipping:
	 $(BUILD) TheLure LinuxArm64 Shipping  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLure: TheLure-Linux-Development

TheLureEditor-Linux-DebugGame:
	 $(BUILD) TheLureEditor Linux DebugGame  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLureEditor-Linux-Development:
	 $(BUILD) TheLureEditor Linux Development  -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" $(ARGS)

TheLureEditor: TheLureEditor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/oleksii/Dev/UnrealEngine_Git/My_TheLure/TheLure/TheLure.uproject" -Game 

.PHONY: $(TARGETS)
